### ISSUE TITLE
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 626 path $[0].camundaFormRef

### ISSUE THREAD

**Issue by jarvis0325** [camunda-community-hub/camunda-platform-7-rest-client-java#83]
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 626 path $[0].camundaFormRef.
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at org.camunda.community.rest.client.invoker.JSON.deserialize(JSON.java:139)
	at org.camunda.community.rest.client.invoker.ApiClient.deserialize(ApiClient.java:782)
	at org.camunda.community.rest.client.invoker.ApiClient.handleResponse(ApiClient.java:988)
	at org.camunda.community.rest.client.invoker.ApiClient.execute(ApiClient.java:912)
	at org.camunda.community.rest.client.api.TaskApi.getTasksWithHttpInfo(TaskApi.java:2127)
	at org.camunda.community.rest.client.api.TaskApi.getTasks(TaskApi.java:2011)
	at com.lbot.CamundaClient.main(CamundaClient.java:40)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 626 path $[0].camundaFormRef.
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 18 more

[
    {
        "id": "4294c016-60d1-11ee-8ab9-005056970dc1",
        "name": "Approve Payment",
        "assignee": "demo",
        "created": "2023-10-02T11:10:37.654+0800",
        "due": null,
        "followUp": null,
        "lastUpdated": null,
        "delegationState": null,
        "description": null,
        "executionId": "429498fe-60d1-11ee-8ab9-005056970dc1",
        "owner": null,
        "parentTaskId": null,
        "priority": 50,
        "processDefinitionId": "payment-retrieval:10:c82ec1f4-5de7-11ee-8ab9-005056970dc1",
        "processInstanceId": "429498fe-60d1-11ee-8ab9-005056970dc1",
        "taskDefinitionKey": "Activity_18lelcs",
        "caseExecutionId": null,
        "caseInstanceId": null,
        "caseDefinitionId": null,
        "suspended": false,
        "formKey": null,
        "camundaFormRef": {
            "key": "paymentform",
            "binding": "deployment",
            "version": null
        },
        "tenantId": null
    },
    {
        "id": "9728d93d-5de3-11ee-a462-005056970dc1",
        "name": "Review Invoice",
        "assignee": "demo",
        "created": "2023-09-28T17:44:17.006+0800",
        "due": "2023-09-30T17:44:17.006+0800",
        "followUp": null,
        "lastUpdated": null,
        "delegationState": null,
        "description": null,
        "executionId": "36dc7175-5de3-11ee-a462-005056970dc1",
        "owner": null,
        "parentTaskId": null,
        "priority": 50,
        "processDefinitionId": "ReviewInvoice:1:dba4068d-5da9-11ee-8a11-005056970dc1",
        "processInstanceId": "36dc7175-5de3-11ee-a462-005056970dc1",
        "taskDefinitionKey": "reviewInvoice",
        "caseExecutionId": null,
        "caseInstanceId": null,
        "caseDefinitionId": null,
        "suspended": false,
        "formKey": "embedded:app:forms/review-invoice.html",
        "camundaFormRef": null,
        "tenantId": null
    },
    {
        "id": "cb1021f4-5de5-11ee-8ab9-005056970dc1",
        "name": "Approve Invoice",
        "assignee": null,
        "created": "2023-09-28T18:00:03.079+0800",
        "due": "2023-10-05T18:00:03.082+0800",
        "followUp": null,
        "lastUpdated": null,
        "delegationState": null,
        "description": "Approve the invoice (or not).",
        "executionId": "caa68a95-5de5-11ee-8ab9-005056970dc1",
        "owner": null,
        "parentTaskId": null,
        "priority": 50,
        "processDefinitionId": "invoice:2:dce33d54-5da9-11ee-8a11-005056970dc1",
        "processInstanceId": "caa68a95-5de5-11ee-8ab9-005056970dc1",
        "taskDefinitionKey": "approveInvoice",
        "caseExecutionId": null,
        "caseInstanceId": null,
        "caseDefinitionId": null,
        "suspended": false,
        "formKey": "embedded:app:forms/approve-invoice.html",
        "camundaFormRef": null,
        "tenantId": null
    },
    {
        "id": "cd09813f-5de5-11ee-8ab9-005056970dc1",
        "name": "Prepare\nBank\nTransfer",
        "assignee": null,
        "created": "2023-09-28T18:00:06.130+0800",
        "due": "2023-10-05T18:00:06.130+0800",
        "followUp": null,
        "lastUpdated": null,
        "delegationState": null,
        "description": "Prepare the bank transfer.",
        "executionId": "cd095a2d-5de5-11ee-8ab9-005056970dc1",
        "owner": null,
        "parentTaskId": null,
        "priority": 50,
        "processDefinitionId": "invoice:2:dce33d54-5da9-11ee-8a11-005056970dc1",
        "processInstanceId": "cce249f5-5de5-11ee-8ab9-005056970dc1",
        "taskDefinitionKey": "prepareBankTransfer",
        "caseExecutionId": null,
        "caseInstanceId": null,
        "caseDefinitionId": null,
        "suspended": false,
        "formKey": "embedded:app:forms/prepare-bank-transfer.html",
        "camundaFormRef": null,
        "tenantId": null
    },
    {
        "id": "cd2a4f06-5de5-11ee-8ab9-005056970dc1",
        "name": "Assign Reviewer",
        "assignee": "demo",
        "created": "2023-09-28T18:00:06.423+0800",
        "due": null,
        "followUp": null,
        "lastUpdated": null,
        "delegationState": null,
        "description": null,
        "executionId": "cd2a00d6-5de5-11ee-8ab9-005056970dc1",
        "owner": null,
        "parentTaskId": null,
        "priority": 50,
        "processDefinitionId": "ReviewInvoice:1:dba4068d-5da9-11ee-8a11-005056970dc1",
        "processInstanceId": "cd2a00d6-5de5-11ee-8ab9-005056970dc1",
        "taskDefinitionKey": "assignReviewer",
        "caseExecutionId": null,
        "caseInstanceId": null,
        "caseDefinitionId": null,
        "suspended": false,
        "formKey": "embedded:app:forms/assign-reviewer.html",
        "camundaFormRef": null,
        "tenantId": null
    }
]

How can i fix this problem ?

**Comment by jonathanlukas** [comment]
@jarvis0325 the latest version of the client uses jackson - could you please try to recreate the issue?
